 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using Nettention.Proud;
namespace C2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID TurnChanged = (Nettention.Proud.RmiID)3000+1;
			public const Nettention.Proud.RmiID Turn = (Nettention.Proud.RmiID)3000+2;
			public const Nettention.Proud.RmiID Draw = (Nettention.Proud.RmiID)3000+3;
			public const Nettention.Proud.RmiID Invalid = (Nettention.Proud.RmiID)3000+4;
			public const Nettention.Proud.RmiID Jump = (Nettention.Proud.RmiID)3000+5;
			public const Nettention.Proud.RmiID Reverse = (Nettention.Proud.RmiID)3000+6;
			public const Nettention.Proud.RmiID ChangeColor = (Nettention.Proud.RmiID)3000+7;
			public const Nettention.Proud.RmiID Timer = (Nettention.Proud.RmiID)3000+8;
			public const Nettention.Proud.RmiID Rank = (Nettention.Proud.RmiID)3000+9;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			TurnChanged,
			Turn,
			Draw,
			Invalid,
			Jump,
			Reverse,
			ChangeColor,
			Timer,
			Rank,
		};
	}
}






				 
