 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using Nettention.Proud;
namespace C2S
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RoomCreate = (Nettention.Proud.RmiID)1000+1;
			public const Nettention.Proud.RmiID JoinRoom = (Nettention.Proud.RmiID)1000+2;
			public const Nettention.Proud.RmiID LeaveRoom = (Nettention.Proud.RmiID)1000+3;
			public const Nettention.Proud.RmiID GameStart = (Nettention.Proud.RmiID)1000+4;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RoomCreate,
			JoinRoom,
			LeaveRoom,
			GameStart,
		};
	}
}






				 
