 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace C2S
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID CreateRoom = (Nettention.Proud.RmiID)1000+1;
			public const Nettention.Proud.RmiID JoinRoom = (Nettention.Proud.RmiID)1000+2;
			public const Nettention.Proud.RmiID LeaveRoom = (Nettention.Proud.RmiID)1000+3;
			public const Nettention.Proud.RmiID Ready = (Nettention.Proud.RmiID)1000+4;
			public const Nettention.Proud.RmiID UnReady = (Nettention.Proud.RmiID)1000+5;
			public const Nettention.Proud.RmiID Down = (Nettention.Proud.RmiID)1000+6;
			public const Nettention.Proud.RmiID Draw = (Nettention.Proud.RmiID)1000+7;
			public const Nettention.Proud.RmiID Attack = (Nettention.Proud.RmiID)1000+8;
			public const Nettention.Proud.RmiID Invalid = (Nettention.Proud.RmiID)1000+9;
			public const Nettention.Proud.RmiID ChangeSymbol = (Nettention.Proud.RmiID)1000+10;
			public const Nettention.Proud.RmiID OneCard = (Nettention.Proud.RmiID)1000+11;
			public const Nettention.Proud.RmiID ZeroCard = (Nettention.Proud.RmiID)1000+12;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			CreateRoom,
			JoinRoom,
			LeaveRoom,
			Ready,
			UnReady,
			Down,
			Draw,
			Attack,
			Invalid,
			ChangeSymbol,
			OneCard,
			ZeroCard,
		};
	}
}






				 
