 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using Nettention.Proud;
namespace S2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Create_OK = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID Create_Fail = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID Join_OK = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID Join_Fail = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID Leave_OK = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID Leave_Fail = (Nettention.Proud.RmiID)2000+6;
			public const Nettention.Proud.RmiID Start_OK = (Nettention.Proud.RmiID)2000+7;
			public const Nettention.Proud.RmiID Start_Fail = (Nettention.Proud.RmiID)2000+8;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Create_OK,
			Create_Fail,
			Join_OK,
			Join_Fail,
			Leave_OK,
			Leave_Fail,
			Start_OK,
			Start_Fail,
		};
	}
}






				 
