 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace S2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Start = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID TurnStart = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID LastCard = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID Draw = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID ChangeSymbol = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID Rank = (Nettention.Proud.RmiID)2000+6;
			public const Nettention.Proud.RmiID ExcludeGame = (Nettention.Proud.RmiID)2000+7;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Start,
			TurnStart,
			LastCard,
			Draw,
			ChangeSymbol,
			Rank,
			ExcludeGame,
		};
	}
}






				 
